spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  security:
    user:
      name: "Abdul"
      password: "password"
    oauth2:
      authorization-server:
        client:
          portfolio-client:
            registration:
              client-id: "portfolio-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
              scopes:
                - "openid"
                - "profile"
              redirect-uris:
                - "https://oauth.pstmn.io/v1/browser-callback"
#            require-authorization-consent: true
server:
  port: 8090
